export const queryKeys = {
  auth: {
    me: ['auth', 'me'] as const,
  },
  catalog: {
    products: (params?: unknown) => ['catalog', 'products', params] as const,
    product: (slug: string) => ['catalog', 'product', slug] as const,
    categories: ['catalog', 'categories'] as const,
    brands: ['catalog', 'brands'] as const,
    featured: ['catalog', 'featured'] as const,
    reviews: (productId: number) => ['catalog', 'reviews', productId] as const,
    queries: (productId: number) => ['catalog', 'queries', productId] as const,
    crossSells: (productId: number) => ['catalog', 'crossSells', productId] as const,
  },
  cart: {
    current: ['cart', 'current'] as const,
    shippingRates: (addressId: number) => ['cart', 'shippingRates', addressId] as const,
  },
  checkout: {
    summary: ['checkout', 'summary'] as const,
    addresses: ['checkout', 'addresses'] as const,
  },
  orders: {
    list: (params?: unknown) => ['orders', 'list', params] as const,
    detail: (orderNumber: string) => ['orders', 'detail', orderNumber] as const,
    tracking: (orderId: number) => ['orders', 'tracking', orderId] as const,
  },
  wishlist: {
    list: ['wishlist'] as const,
  },
  cms: {
    posts: (params?: unknown) => ['cms', 'posts', params] as const,
    post: (slug: string) => ['cms', 'post', slug] as const,
    page: (slug: string) => ['cms', 'page', slug] as const,
    faqs: ['cms', 'faqs'] as const,
    banners: (position?: string) => ['cms', 'banners', position] as const,
    alerts: ['cms', 'alerts'] as const,
    popups: ['cms', 'popups'] as const,
    settings: ['cms', 'settings'] as const,
    menus: (location: string) => ['cms', 'menus', location] as const,
  },
  admin: {
    dashboard: (period: string) => ['admin', 'dashboard', period] as const,
    analytics: (type: string, params?: unknown) => ['admin', 'analytics', type, params] as const,
    exportJob: (id: number) => ['admin', 'exports', id] as const,
    products: (params?: unknown) => ['admin', 'products', params] as const,
    product: (id: number) => ['admin', 'products', id] as const,
    orders: (params?: unknown) => ['admin', 'orders', params] as const,
    order: (id: number) => ['admin', 'orders', id] as const,
    orderTracking: (id: number) => ['admin', 'orders', id, 'tracking'] as const,
    returns: (params?: unknown) => ['admin', 'returns', params] as const,
    returnDetail: (id: number) => ['admin', 'returns', id] as const,
    payments: (params?: unknown) => ['admin', 'payments', params] as const,
    paymentMethods: () => ['admin', 'payment-methods'] as const,
    shipments: (params?: unknown) => ['admin', 'shipments', params] as const,
    shipment: (id: number) => ['admin', 'shipments', id] as const,
    omsSummary: () => ['admin', 'oms-summary'] as const,
    notifications: (params?: unknown) => ['admin', 'notifications', params] as const,
    activityLogs: (params?: unknown) => ['admin', 'activity-logs', params] as const,
    admins: (params?: unknown) => ['admin', 'admins', params] as const,
    customers: (params?: unknown) => ['admin', 'customers', params] as const,
    inventory: (params?: unknown) => ['admin', 'inventory', params] as const,
    categories: (params?: unknown) => ['admin', 'categories', params] as const,
    brands: (params?: unknown) => ['admin', 'brands', params] as const,
    reviews: (params?: unknown) => ['admin', 'reviews', params] as const,
    productQueries: (params?: unknown) => ['admin', 'productQueries', params] as const,
    pages: (params?: unknown) => ['admin', 'pages', params] as const,
    posts: (params?: unknown) => ['admin', 'posts', params] as const,
    banners: (params?: unknown) => ['admin', 'banners', params] as const,
    faqs: (params?: unknown) => ['admin', 'faqs', params] as const,
    media: (params?: unknown) => ['admin', 'media', params] as const,
    settings: (group?: string) => ['admin', 'settings', group] as const,
    alerts: (params?: unknown) => ['admin', 'alerts', params] as const,
    popups: (params?: unknown) => ['admin', 'popups', params] as const,
    contactMessages: (params?: unknown) => ['admin', 'contactMessages', params] as const,
    subscribers: (params?: unknown) => ['admin', 'subscribers', params] as const,
    notificationTemplates: (params?: unknown) => ['admin', 'notificationTemplates', params] as const,
    modules: (params?: unknown) => ['admin', 'modules', params] as const,
    module: (id: number) => ['admin', 'modules', id] as const,
    moduleHealth: (id: number) => ['admin', 'modules', id, 'health'] as const,
    // Phase 10: Attributes, Colors, Size Charts, Warranties
    attributes: (params?: unknown) => ['admin', 'attributes', params] as const,
    attribute: (id: number) => ['admin', 'attributes', id] as const,
    colors: (params?: unknown) => ['admin', 'colors', params] as const,
    sizeCharts: (params?: unknown) => ['admin', 'sizeCharts', params] as const,
    sizeChart: (id: number) => ['admin', 'sizeCharts', id] as const,
    warranties: (params?: unknown) => ['admin', 'warranties', params] as const,
    warranty: (id: number) => ['admin', 'warranties', id] as const,
    // Phase 11: Reports
    stockReport: (params?: unknown) => ['admin', 'analytics', 'stock', params] as const,
    wishlistReport: ['admin', 'analytics', 'wishlist'] as const,
    categoryReport: ['admin', 'analytics', 'categories'] as const,
    // Phase 13: Media
    mediaStats: ['admin', 'media', 'stats'] as const,
    mediaItem: (id: number) => ['admin', 'media', id] as const,
    // Phase 18: Review stats
    reviewStats: ['admin', 'reviews', 'statistics'] as const,
    // Phase 20: System
    systemInfo: ['admin', 'system', 'info'] as const,
    systemHealth: ['admin', 'system', 'health'] as const,
    dbStats: ['admin', 'system', 'dbStats'] as const,
  },
};
