<?php

return [
    'products' => [
        [
            'name' => 'Poondu Thokku',
            'slug' => 'poondu-thokku',
            'price' => 179,
            'compare_at_price' => 225,
            'short_description' => 'Bold garlic mashed pickle.',
            'description' => '<p>Whole garlic cloves slow-cooked with tamarind, red chili, and cold-pressed sesame oil. A spicy, pungent thokku perfect with hot rice and curd rice.</p>',
            'image_path' => '/images/products/Poondu Thokku (Garlic Mashed Pickle).jpg',
            'sku' => 'PnT-250',
            'stock_quantity' => 45,
            'unit' => '250g Jar',
            'tags' => ['Thokku', 'Bestseller'],
        ],
        [
            'name' => 'Karuveppilai Thokku',
            'slug' => 'karuveppilai-thokku',
            'price' => 179,
            'compare_at_price' => 225,
            'short_description' => 'Flavor-packed curry leaves mashed pickle.',
            'description' => '<p>Fresh curry leaves ground and slow-cooked with tamarind, spices, and cold-pressed oil. Excellent for hair growth and digestion.</p>',
            'image_path' => '/images/products/Karuveppilai Thokku (Curry Leaves Mashed Pickle).jpg',
            'sku' => 'KVT-250',
            'stock_quantity' => 50,
            'unit' => '250g Jar',
            'tags' => ['Thokku', 'Bestseller'],
        ],
        [
            'name' => 'Pavakai Thokku',
            'slug' => 'pavakai-thokku',
            'price' => 159,
            'compare_at_price' => 199,
            'short_description' => 'Sweet, sour, and mildly bitter gourd thokku.',
            'description' => '<p>Bitter gourd slow-cooked with tamarind, jaggery, and spices. A unique blend of sweet, sour, and bitter notes that tastes incredible with rice.</p>',
            'image_path' => '/images/products/Paakarkaai Thokku (Bitter Gourd Mashed Pickle).jpg',
            'sku' => 'PT-250',
            'stock_quantity' => 40,
            'unit' => '250g Jar',
            'tags' => ['Thokku', 'Health'],
        ],
        [
            'name' => 'Pirandai Thokku',
            'slug' => 'pirandai-thokku',
            'price' => 199,
            'compare_at_price' => 249,
            'short_description' => 'Bone-strengthening adamant creeper thokku.',
            'description' => '<p>Pirandai (Adamant Creeper) slow-cooked with tamarind and spices. Known in Siddha medicine for strengthening bones and improving calcium absorption.</p>',
            'image_path' => '/images/products/Pirandai Thokku (Adamant Creeper Mashed Pickle).jpg',
            'sku' => 'PiT-250',
            'stock_quantity' => 30,
            'unit' => '250g Jar',
            'tags' => ['Thokku', 'Health'],
        ],
        [
            'name' => 'Valaipoo Thokku',
            'slug' => 'valaipoo-thokku',
            'price' => 199,
            'compare_at_price' => 249,
            'short_description' => 'Traditional banana blossom thokku.',
            'description' => '<p>A classic South Indian condiment made from fresh banana blossoms, slow-cooked with mustard, fenugreek, and a secret blend of spices. Perfect with rice, dosa, or idli.</p>',
            'image_path' => '/images/products/Vazhaippu Thokku (Bannana Leaf Mashed Pickle).jpg',
            'sku' => 'VZ-250',
            'stock_quantity' => 40,
            'unit' => '250g Jar',
            'tags' => ['Thokku'],
        ],
        [
            'name' => 'Thakkali Thokku',
            'slug' => 'thakkali-thokku',
            'price' => 159,
            'compare_at_price' => 199,
            'short_description' => 'Tangy tomato mashed pickle.',
            'description' => '<p>Ripe tomatoes slow-cooked to a thick, tangy paste with mustard, fenugreek, and aromatic spices. A versatile thokku that pairs beautifully with dosa, idli, and rice.</p>',
            'image_path' => '/images/products/Thakkali Thokku (Tomato Mashed Pickle).jpg',
            'sku' => 'TT-250',
            'stock_quantity' => 55,
            'unit' => '250g Jar',
            'tags' => ['Thokku', 'Bestseller'],
        ],
        [
            'name' => 'Vallarai Thokku',
            'slug' => 'vallarai-thokku',
            'price' => 179,
            'compare_at_price' => 225,
            'short_description' => 'Nutritious brahmi leaves mashed pickle.',
            'description' => '<p>A healthy thokku made from fresh Vallarai (Centella) leaves, offering both medicinal benefits and a tangy, spicy flavor profile.</p>',
            'image_path' => '/images/products/Vallarai Thokku (Centella  Brahmi Mashed Pickle).jpg',
            'sku' => 'VAT-250',
            'stock_quantity' => 35,
            'unit' => '250g Jar',
            'tags' => ['Thokku', 'Health'],
        ],
        [
            'name' => 'Mallithalai Thokku',
            'slug' => 'mallithalai-thokku',
            'price' => 159,
            'compare_at_price' => 199,
            'short_description' => 'Fresh coriander mashed pickle.',
            'description' => '<p>A refreshing coriander thokku made with fresh coriander leaves, green chili, and traditional spices. Adds a vibrant, herby kick to any meal.</p>',
            'image_path' => '/images/products/Mallithalai Thokku (Coriander Mashed Pickle).jpg',
            'sku' => 'MT-250',
            'stock_quantity' => 25,
            'unit' => '250g Jar',
            'tags' => ['Thokku'],
        ],
        [
            'name' => 'Chinavangayam Thokku',
            'slug' => 'chinavangayam-thokku',
            'price' => 179,
            'compare_at_price' => 225,
            'short_description' => 'Authentic shallot mashed pickle with rich flavors.',
            'description' => '<p>A flavorful South Indian delicacy made with fresh shallots, slow-cooked with tamarind and a blend of traditional spices. Perfect as a side for rice, idli, or dosa.</p>',
            'image_path' => '/images/products/Chinnavengayam Thokku (Shallot Mashed Pickle).jpg',
            'sku' => 'CT-250',
            'stock_quantity' => 45,
            'unit' => '250g Jar',
            'tags' => ['Thokku', 'Bestseller'],
        ],
        [
            'name' => 'Kovakkai Thokku',
            'slug' => 'kovakkai-thokku',
            'price' => 179,
            'compare_at_price' => 225,
            'short_description' => 'Tangy ivy gourd mashed pickle.',
            'description' => '<p>Fresh ivy gourd (kovakkai) slow-cooked with mustard, fenugreek, and traditional spices. A diabetic-friendly thokku with amazing flavors.</p>',
            'image_path' => '/images/products/Kovakkai Thokku (Ivy Gourd Mashed Pickle).jpg',
            'sku' => 'KK-250',
            'stock_quantity' => 30,
            'unit' => '250g Jar',
            'tags' => ['Thokku', 'Health'],
        ],
        [
            'name' => 'Lemon Urukai',
            'slug' => 'lemon-urukai',
            'price' => 149,
            'compare_at_price' => 189,
            'short_description' => 'Zesty lemon pickle with a spicy punch.',
            'description' => '<p>Elumichai (lemon) marinated with rock salt, chili powder, and traditional spices. A zesty, tangy pickle that adds life to any South Indian meal.</p>',
            'image_path' => '/images/products/Lime Pickle (Elumichai Oorugai).jpg',
            'sku' => 'LU-250',
            'stock_quantity' => 40,
            'unit' => '250g Jar',
            'tags' => ['Urukai'],
        ],
        [
            'name' => 'Narthangai Urukai',
            'slug' => 'narthangai-urukai',
            'price' => 149,
            'compare_at_price' => 189,
            'short_description' => 'Aromatic citron pickle with tangy notes.',
            'description' => '<p>Narthangai (citron) marinated with mustard, fenugreek, and cold-pressed oil. A tangy, fragrant pickle that brings a burst of citrus to every meal.</p>',
            'image_path' => '/images/products/Citron Pickle (Narthangai Oorugai).jpg',
            'sku' => 'NU-250',
            'stock_quantity' => 35,
            'unit' => '250g Jar',
            'tags' => ['Urukai'],
        ],
        [
            'name' => 'Maangai Urukai',
            'slug' => 'maangai-urukai',
            'price' => 149,
            'compare_at_price' => 189,
            'short_description' => 'Tangy and spicy traditional mango pickle.',
            'description' => '<p>Made with hand-picked raw mangoes, mustard, fenugreek, and cold-pressed gingelly oil. Sun-dried for days to achieve the perfect crunch and flavor.</p>',
            'image_path' => '/images/products/Maanga Oorugai(Mango Pickle).jpg',
            'sku' => 'MU-250',
            'stock_quantity' => 70,
            'unit' => '250g Jar',
            'tags' => ['Urukai', 'Bestseller'],
        ],
        [
            'name' => 'Idly Podi',
            'slug' => 'idly-podi',
            'price' => 99,
            'compare_at_price' => 129,
            'short_description' => 'Classic roasted spice powder for idli and dosa.',
            'description' => '<p>A quintessential South Indian breakfast companion. Roasted lentils and red chillies ground to a coarse, flavourful powder. Perfect with idli, dosa, and sesame oil.</p>',
            'image_path' => '/images/products/Idly Podi (Idli Spice Mix).jpg',
            'sku' => 'IP-150',
            'stock_quantity' => 60,
            'unit' => '150g Jar',
            'tags' => ['Podi', 'Bestseller'],
        ],
        [
            'name' => 'Paruppu Podi',
            'slug' => 'paruppu-podi',
            'price' => 99,
            'compare_at_price' => 129,
            'short_description' => 'Classic dal spice mix for rice.',
            'description' => '<p>A staple South Indian comfort food made by roasting toor dal, roasted gram, and mild spices. Best enjoyed with hot steamed rice and a dollop of ghee.</p>',
            'image_path' => '/images/products/Paruppu Podi (Dal Powder or Dal Spice Mix).jpg',
            'sku' => 'PP-150',
            'stock_quantity' => 65,
            'unit' => '150g Jar',
            'tags' => ['Podi', 'Bestseller'],
        ],
        [
            'name' => 'Poondu Podi',
            'slug' => 'poondu-podi',
            'price' => 109,
            'compare_at_price' => 139,
            'short_description' => 'Flavorful garlic spice mix.',
            'description' => '<p>A pungent and flavorful blend of roasted garlic, red chilies, and lentils. Perfect for spicing up your idlis, dosas, or plain rice.</p>',
            'image_path' => '/images/products/Poondu Podi (Garlic Powder or Garlic Spice Mix).jpg',
            'sku' => 'PoP-150',
            'stock_quantity' => 45,
            'unit' => '150g Jar',
            'tags' => ['Podi', 'Bestseller'],
        ],
        [
            'name' => 'Karuveppilai Podi',
            'slug' => 'karuveppilai-podi',
            'price' => 109,
            'compare_at_price' => 139,
            'short_description' => 'Aromatic curry leaf powder rich in iron.',
            'description' => '<p>Fresh curry leaves dried and ground with urad dal, chana dal, and spices. Sprinkle on hot rice with a drizzle of ghee or use as a side for idli/dosa.</p>',
            'image_path' => '/images/products/Karuveppilai Podi (Curry Leaves Spice Mix or Curry Leaves Powder).jpg',
            'sku' => 'KVP-150',
            'stock_quantity' => 60,
            'unit' => '150g Jar',
            'tags' => ['Podi', 'Health'],
        ],
        [
            'name' => 'Nilakadalai Podi',
            'slug' => 'nilakadalai-podi',
            'price' => 119,
            'compare_at_price' => 149,
            'short_description' => 'Crunchy groundnut spice mix.',
            'description' => '<p>Roasted peanuts ground with dried coconut, red chili, and garlic. A protein-rich powder that makes idli/dosa breakfast extra special.</p>',
            'image_path' => '/images/products/Nilakadalai Podi (Groundnut  Spice Mix or (Groundnut  Powder).jpg',
            'sku' => 'NP-150',
            'stock_quantity' => 50,
            'unit' => '150g Jar',
            'tags' => ['Podi', 'Bestseller'],
        ],
        [
            'name' => 'Ellu Podi',
            'slug' => 'ellu-podi',
            'price' => 129,
            'compare_at_price' => 159,
            'short_description' => 'Nutty black sesame spice mix.',
            'description' => '<p>Roasted black sesame seeds ground with lentils, dried chili, and a touch of asafoetida. Calcium-rich and incredibly flavorful when mixed with hot rice and ghee.</p>',
            'image_path' => '/images/products/Ellu Podi (Black Sesame Spice Mix or Black Sesame Powder).jpg',
            'sku' => 'EP-150',
            'stock_quantity' => 40,
            'unit' => '150g Jar',
            'tags' => ['Podi', 'Health'],
        ],
        [
            'name' => 'Kollu Podi',
            'slug' => 'kollu-podi',
            'price' => 119,
            'compare_at_price' => 149,
            'short_description' => 'Nutritious horse gram spice mix.',
            'description' => '<p>Roasted horse gram blended with traditional spices. Known for its weight management properties, this podi is both healthy and delicious.</p>',
            'image_path' => '/images/products/Kollu Podi ( Horse gram Spice Mix or Horse gram Powder).jpg',
            'sku' => 'KP-150',
            'stock_quantity' => 45,
            'unit' => '150g Jar',
            'tags' => ['Podi', 'Health'],
        ],
        [
            'name' => 'Murungai Podi',
            'slug' => 'murungai-podi',
            'price' => 129,
            'compare_at_price' => 159,
            'short_description' => 'Super-food moringa spice mix.',
            'description' => '<p>Dried moringa leaves blended with lentils and spices. A powerhouse of vitamins and minerals, adding a healthy kick to your daily meals.</p>',
            'image_path' => '/images/products/Murungai Keerai Podi (Moringa Spice Mix or (Moringa Powder).jpg',
            'sku' => 'MKP-150',
            'stock_quantity' => 55,
            'unit' => '150g Jar',
            'tags' => ['Podi', 'Superfood', 'Health'],
        ],
        [
            'name' => 'Pirandai Podi',
            'slug' => 'pirandai-podi',
            'price' => 129,
            'compare_at_price' => 159,
            'short_description' => 'Bone-strengthening veldt grape spice mix.',
            'description' => '<p>Pirandai (Adamant Creeper / Veldt grape) dried and roasted with lentils. Known in traditional medicine to strengthen bones and improve digestion.</p>',
            'image_path' => '/images/products/Pirandai Podi (Veldt Grape Powder or Veldt Grape Spice Mix).jpg',
            'sku' => 'PiP-150',
            'stock_quantity' => 35,
            'unit' => '150g Jar',
            'tags' => ['Podi', 'Health'],
        ],
        [
            'name' => 'Vallarai Podi',
            'slug' => 'vallarai-podi',
            'price' => 129,
            'compare_at_price' => 159,
            'short_description' => 'Brain-boosting brahmi leaf powder.',
            'description' => '<p>Sun-dried and stone-ground Vallarai (Brahmi) leaves blended with dal and spices. Known for its cognitive boosting properties.</p>',
            'image_path' => '/images/products/Vallarai Podi (Centella Powder or Centella Spice Mix ).jpg',
            'sku' => 'VAP-150',
            'stock_quantity' => 40,
            'unit' => '150g Jar',
            'tags' => ['Podi', 'Health'],
        ],
        [
            'name' => 'Sambar Podi',
            'slug' => 'sambar-podi',
            'price' => 149,
            'compare_at_price' => 189,
            'short_description' => 'Traditional sambar powder blend.',
            'description' => '<p>A fragrant blend of roasted coriander, cumin, fenugreek, red chillies, and lentils. The heart of every South Indian sambar, freshly ground in small batches.</p>',
            'image_path' => '/images/products/Sambar Podi (Sambar Powder).jpg',
            'sku' => 'SP-150',
            'stock_quantity' => 50,
            'unit' => '150g Jar',
            'tags' => ['Podi', 'Bestseller'],
        ],
        [
            'name' => 'Pulikulambu Podi',
            'slug' => 'pulikulambu-podi',
            'price' => 149,
            'compare_at_price' => 189,
            'short_description' => 'Spice mix for tangy tamarind curry.',
            'description' => '<p>A carefully crafted spice blend for the beloved Tamil tamarind curry. Balanced heat, tang, and warmth for effortless authentic pulikulambu.</p>',
            'image_path' => '/images/products/Pulikulambu Podi (Tamarind Curry Powder).jpg',
            'sku' => 'PuP-150',
            'stock_quantity' => 40,
            'unit' => '150g Jar',
            'tags' => ['Podi'],
        ],
        [
            'name' => 'Karikulambu Podi',
            'slug' => 'karikulambu-podi',
            'price' => 149,
            'compare_at_price' => 189,
            'short_description' => 'Robust black curry spice mix.',
            'description' => '<p>A bold, deeply roasted spice blend for the iconic Tamil black curry. Smoky, robust character that brings authentic depth to this beloved everyday dish.</p>',
            'image_path' => '/images/products/Karikulambu Podi (Black Curry Powder).jpg',
            'sku' => 'KKP-150',
            'stock_quantity' => 35,
            'unit' => '150g Jar',
            'tags' => ['Podi'],
        ],
        [
            'name' => 'Rasa Podi',
            'slug' => 'rasa-podi',
            'price' => 149,
            'compare_at_price' => 189,
            'short_description' => 'Traditional rasam powder blend.',
            'description' => '<p>A classic pepper-forward rasam powder ground fresh with black pepper, cumin, coriander, and garlic. Makes preparing comforting South Indian rasam quick and easy.</p>',
            'image_path' => '/images/products/Rasa Podi (Rasam Powder).jpg',
            'sku' => 'RP-150',
            'stock_quantity' => 45,
            'unit' => '150g Jar',
            'tags' => ['Podi'],
        ],
    ],
    'blog_banners' => [
        'art-of-traditional-pickle-making' => '/images/blog/traditional-pickle-making.png',
        'health-benefits-curry-leaves' => '/images/blog/curry-leaves-health.png',
        'perfect-podi-pairings' => '/images/blog/podi-pairings.png',
    ],
    'contact' => [
        'description' => 'We would love to hear from you. Reach out for orders, product questions, feedback, or store support.',
        'email' => 'dhanvanthrifoods777@gmail.com',
        'phone' => '9445717977',
        'address' => 'Dhanvanthiri Foods, Erode, Tamil Nadu, India',
    ],
];
