
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','Sitemap URL','Sitemap URL',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('bd','Sitemap URL','Sitemap URL',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('sa','Sitemap URL','عنوان URL لخريطة الموقع',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('es','Sitemap URL','URL del mapa del sitio',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('jp','Sitemap URL','サイトマップURL',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('fr','Sitemap URL','URL du plan du site',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('in','Sitemap URL','साइटमैप यूआरएल',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('nl','Sitemap URL','Sitemap-URL',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('af','Sitemap URL','Werfkaart-URL',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('eg','Sitemap URL','عنوان URL لخريطة الموقع',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('za','Sitemap URL','Khariidadda goobta URL',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','Sitemap URL','URL léarscáil an tSuímh',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('sg','Sitemap URL','URL peta tapak',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('vn','Sitemap URL','URL sơ đồ trang web',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('my','Sitemap URL','URL peta tapak',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('lk','Sitemap URL','தளவரைபட URL',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ke','Sitemap URL','Uuzaji wa Flash',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('th','Sitemap URL','แผนผังเว็บไซต์ URL',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('cn','Sitemap URL','網站地圖網址',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('zw','Sitemap URL','Sitemap URL',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('pk','Sitemap URL','سائٹ کا نقشہ URL',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('tr','Sitemap URL','Site Haritası URL\'si',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','please_select_seller_first','Please Select Seller first.',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','edit_seller_custom_followers','Edit Seller Custom Followers',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','commission_percentage','Commission Percentage',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','selle_commission','Selle Commission',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','set_seller_commission','Set Seller Commission',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','do_you_really_want_to_unban_this_seller','Do you really want to unban this seller?',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','set_commission','Set Commission',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','regular','Regular',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','unverified','Unverified',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','verified','Verified',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','filter_by_verification_status','Filter by Verification Status',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','set_bulk_commission','Set Bulk Commission',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','reply','Reply',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','query','Query',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','sitemap_url','Sitemap URL',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('en','invalid_login_credentials','Invalid login credentials',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('tr','Download File','Dosyayı İndir',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('tr','Delete File','Dosyayı Sil',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('tr','Mime Type','Mim Türü',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('tr','Last Modified','Son Değiştirilme Tarihi',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('tr','File Size','Dosya Boyutu',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('tr','File Name','Dosya adı',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('tr','Sitemap Generation History','Site Haritası Oluşturma Geçmişi',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('tr','Generate and Download','Oluştur ve İndir',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('pk','Download File','فائل ڈاؤن لوڈ کریں۔',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('pk','Delete File','فائل کو حذف کریں۔',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('pk','Mime Type','مائم کی قسم',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('pk','Last Modified','آخری بار ترمیم کی گئی۔',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('pk','File Size','فائل کا سائز',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('pk','File Name','فائل کا نام',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('pk','Sitemap Generation History','سائٹ میپ جنریشن ہسٹری',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('pk','Generate and Download','بنائیں اور ڈاؤن لوڈ کریں۔',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('zw','Download File','Dhaunirodha File',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('zw','Delete File','Delete File',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('zw','Mime Type','Mime Type',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('zw','Last Modified','Last Modified',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('zw','File Size','Saizi Yefaira',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('zw','File Name','File Name',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('zw','Sitemap Generation History','Sitemap Generation History',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('zw','Generate and Download','Gadzira uye Dhawunirodha',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('cn','Download File','下载文件',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('cn','Delete File','删除文件',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('cn','Mime Type','Mime 类型',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('cn','Last Modified','上次修改',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('cn','File Size','文件大小',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('cn','File Name','文件名',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('cn','Sitemap Generation History','网站地图生成历史',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('cn','Generate and Download','生成并下载',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('th','Download File','ดาวน์โหลดไฟล์',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('th','Delete File','ลบไฟล์',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('th','Mime Type','ประเภท MIME',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('th','Last Modified','ปรับปรุงล่าสุด',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('th','File Size','ขนาดไฟล์',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('th','File Name','ชื่อไฟล์',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('th','Sitemap Generation History','ประวัติการสร้างแผนผังเว็บไซต์',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('th','Generate and Download','สร้างและดาวน์โหลด',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ke','Download File','Pakua Faili',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ke','Delete File','Futa Faili',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ke','Mime Type','Aina ya Mime',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ke','Last Modified','Iliyorekebishwa Mwisho',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ke','File Size','Ukubwa wa Faili',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ke','File Name','Jina la Faili',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ke','Sitemap Generation History','Historia ya Kizazi cha ramani ya tovuti',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ke','Generate and Download','Tengeneza na Upakue',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('lk','Download File','கோப்பைப் பதிவிறக்கு',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('lk','Delete File','கோப்பை நீக்கு',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('lk','Mime Type','மைம் வகை',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('lk','Last Modified','கடைசியாக மாற்றப்பட்டது',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('lk','File Size','கோப்பு அளவு',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('lk','File Name','கோப்பு பெயர்',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('lk','Sitemap Generation History','தளவரைபட தலைமுறை வரலாறு',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('lk','Generate and Download','உருவாக்கி பதிவிறக்கு',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('my','Download File','Muat turun Fail',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('my','Delete File','Padam Fail',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('my','Mime Type','Jenis Mime',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('my','Last Modified','Terakhir Diubah Suai',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('my','File Size','Saiz Fail',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('my','File Name','Nama Fail',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('my','Sitemap Generation History','Sejarah Penjanaan Peta Laman',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('my','Generate and Download','Hasilkan dan Muat turun',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('vn','Download File','Tải xuống tập tin',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('vn','Delete File','Xóa tập tin',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('vn','Mime Type','Kiểu kịch câm',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('vn','Last Modified','Lần sửa đổi cuối cùng',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('vn','File Size','Kích thước tập tin',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('vn','File Name','Tên tập tin',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('vn','Sitemap Generation History','Lịch sử thế hệ sơ đồ trang web',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('vn','Generate and Download','Tạo và Tải xuống',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','Download File','Unduh Berkas',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','Delete File','Hapus File',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','Mime Type','Tipe Mime',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','Last Modified','Terakhir Diubah',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','File Size','Ukuran Berkas',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','File Name','Nama Berkas',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','Sitemap Generation History','Riwayat Pembuatan Peta Situs',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','Generate and Download','Hasilkan dan Unduh',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','Download File','Íoslódáil Comhad',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','Delete File','Scrios Comhad',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','Mime Type','Cineál Míme',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','Last Modified','Athraithe Deiridh',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','File Size','Méid an Chomhaid',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','File Name','Ainm an Chomhaid',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','Sitemap Generation History','Stair Ghiniúint Léarscáil an tSuímh',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('ie','Generate and Download','A chruthú agus a íoslódáil',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('za','Download File','Soo deji faylka',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('za','Delete File','Tirtir Faylka',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('za','Mime Type','Nooca Mime',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('za','Last Modified','Waxka bedelka u dambeeyay',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('za','File Size','Cabbirka faylka',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('za','File Name','Magaca faylka',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('za','Sitemap Generation History','Taariikhda Jiilka Maabka',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('za','Generate and Download','Abuur oo soo deji',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('eg','Download File','تنزيل الملف',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('eg','Delete File','حذف الملف',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('eg','Mime Type','نوع المايم',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('eg','Last Modified','آخر تعديل',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('eg','File Size','حجم الملف',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('eg','File Name','اسم الملف',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('eg','Sitemap Generation History','خريطة الموقع تاريخ الإنشاء',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('eg','Generate and Download','إنشاء وتنزيل',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('af','Download File','Laai lêer af',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('af','Delete File','Vee lêer uit',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('af','Mime Type','Mime tipe',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('af','Last Modified','Laas gewysig',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('af','File Size','Lêergrootte',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('af','File Name','Lêernaam',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('af','Sitemap Generation History','Sitemap Generasie Geskiedenis',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('af','Generate and Download','Genereer en laai af',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('nl','Download File','Bestand downloaden',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('nl','Delete File','Bestand verwijderen',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('nl','Mime Type','Mime-type',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('nl','Last Modified','Laatst gewijzigd',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('nl','File Size','Bestandsgrootte',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('nl','File Name','Bestandsnaam',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('nl','Sitemap Generation History','Sitemap Generatiegeschiedenis',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('nl','Generate and Download','Genereren en downloaden',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('in','Download File','डाउनलोड फ़ाइल',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('in','Delete File','फ़ाइल नष्ट करें',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('in','Mime Type','माइम प्रकार',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('in','Last Modified','अंतिम संशोधित',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('in','File Size','फ़ाइल का साइज़',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('in','File Name','फ़ाइल का नाम',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('in','Sitemap Generation History','साइटमैप निर्माण इतिहास',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('in','Generate and Download','उत्पन्न करें और डाउनलोड करें',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('fr','Download File','Télécharger le fichier',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('fr','Delete File','Supprimer le fichier',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('fr','Mime Type','Type MIME',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('fr','Last Modified','Dernière modification',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('fr','File Size','Taille du fichier',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('fr','File Name','Nom de fichier',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('fr','Sitemap Generation History','Historique de génération du plan du site',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('fr','Generate and Download','Générer et télécharger',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('jp','Download File','ファイルをダウンロード',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('jp','Delete File','ファイルを削除',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('jp','Mime Type','MIMEタイプ',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('jp','Last Modified','最終更新日',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('jp','File Size','ファイルサイズ',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('jp','File Name','ファイル名',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('jp','Sitemap Generation History','サイトマップ生成履歴',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('jp','Generate and Download','生成してダウンロード',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('es','Generate and Download','Generar y descargar',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('es','Sitemap Generation History','Historial de generación de mapas del sitio',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('es','File Name','Nombre del archivo',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('es','File Size','Tamaño del archivo',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('es','Last Modified','Última modificación',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('es','Mime Type','Tipo MIME',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('es','Delete File','Eliminar archivo',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('es','Download File','Descargar archivo',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('bd','Generate and Download','Generate and Download',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('bd','Sitemap Generation History','Sitemap Generation History',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('bd','File Name','File Name',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('bd','File Size','File Size',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('bd','Last Modified','Last Modified',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('bd','Mime Type','Mime Type',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('bd','Delete File','Delete File',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('bd','Download File','Download File',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('sa','Download File','تنزيل الملف',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('sa','Delete File','حذف الملف',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('sa','Mime Type','نوع المايم',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('sa','Last Modified','آخر تعديل',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('sa','File Size','حجم الملف',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('sa','File Name','اسم الملف',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('sa','Sitemap Generation History','خريطة الموقع تاريخ الإنشاء',now());
INSERT INTO `translations` (`lang`, `lang_key`, `lang_value`, `created_at`) values('sa','Generate and Download','إنشاء وتنزيل',now());


INSERT INTO `email_templates` (`id`, `receiver`, `identifier`, `email_type`, `subject`, `default_text`, `status`, `is_status_changeable`, `is_dafault_text_editable`, `addon`, `created_at`, `updated_at`) 
VALUES
(null, 'customer', 'email_verification_for_registration_customer', 'Email Verification for Registration', 'Email Verification on [[store_name]]', '<span id=\"docs-internal-guid-b30785bd-7fff-1e0b-e705-8fd54008f465\"><p dir="ltr" style="line-height:1.38;margin-top:12pt;margin-bottom:12pt;"><span style="font-size: 11pt; font-family: Roboto, sans-serif; background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;">Dear Customer,</span></p> <p dir=\"ltr\" style=\"margin-top: 12pt; margin-bottom: 12pt; line-height: 1.38;\"><span style=\"background-color: transparent; font-family: Roboto, sans-serif; font-size: 11pt; white-space-collapse: preserve;\">Thank you for choosing [[store_name]]! We’re thrilled to welcome you to our community.</span></p><p dir=\"ltr\" style=\"margin-top: 12pt; margin-bottom: 12pt; line-height: 1.38;\"><font face=\"Roboto, sans-serif\"><span style=\"font-size: 14.6667px; white-space-collapse: preserve;\">Your email verification code is [[code]]</span></font></p><p dir=\"ltr\" style=\"margin-top: 12pt; margin-bottom: 12pt; line-height: 1.38;\"><span style=\"font-size: 11pt; font-family: Roboto, sans-serif; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;\">For any questions or concerns, feel free to contact us at </span><span style=\"font-size: 11pt; font-family: Roboto, sans-serif; background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;\">[[admin_email]]</span><span style=\"font-size: 11pt; font-family: Roboto, sans-serif; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;\">.</span></p><p dir=\"ltr\" style=\"margin-top: 12pt; margin-bottom: 12pt; line-height: 1.38;\"><span style=\"font-size: 11pt; font-family: Roboto, sans-serif; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;\">Thank you,</span><span style=\"font-size: 11pt; font-family: Roboto, sans-serif; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;\"><br></span><span style=\"font-size: 11pt; font-family: Roboto, sans-serif; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;\">The [[store_name]] Team</span></p><div><span style=\"font-size: 11pt; font-family: Roboto, sans-serif; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; vertical-align: baseline; white-space-collapse: preserve;\"><br></span></div></span>', 1, 0, 1, NULL, '2024-09-04 00:31:38', '2025-01-15 10:37:36');


UPDATE `business_settings` SET `value` = '9.9' WHERE `business_settings`.`type` = 'current_version';

COMMIT;